export const APP_ROUTES = {
  home: "/",
  login: "/Login",
  register: "/Register",
  accountVerify: "/auth/account-verify",
  resetPassword: "/reset-password",
  connections: "/Connections",
  source: "/Source",
  dataProfiling: "/DataProfiling",
  dataShifting: "/DataShifting",
  kdeDashboard: "/KDEDashboard",
  sqlDashboard: "/SqlDashboard",
  postgresDashboard: "/PostgresDashboard",
  csvDashboard: "/csvDashboard",
  excelUpload: "/excel",
  csvUpload: "/csv",
  kafkaDashboard: "/KafkaDashboard",
  restApiDashboard: "/RestapiDashboard",
};

export const DASHBOARD_ROUTES = [
  { path: APP_ROUTES.connections, page: "Connection" },
  { path: APP_ROUTES.source, page: "Source" },
  { path: APP_ROUTES.dataShifting, page: "DataShifting" },
  { path: APP_ROUTES.kdeDashboard, page: "KDEDashboard" },
  { path: APP_ROUTES.dataProfiling, page: "DataProfiling" },
  { path: APP_ROUTES.sqlDashboard, page: "SqlDashboard" },
  { path: APP_ROUTES.postgresDashboard, page: "PostgresDashboard" },
  { path: APP_ROUTES.csvDashboard, page: "CsvDashboard" },
  { path: APP_ROUTES.excelUpload, page: "CsvDashboard" },
  { path: APP_ROUTES.csvUpload, page: "CsvDashboard" },
  { path: APP_ROUTES.kafkaDashboard, page: "KafkaDashboard" },
  { path: APP_ROUTES.restApiDashboard, page: "RestapiDashboard" },
];
